language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile: Gemfile
after_install: gem list
script: bundle exec rake spec
notifications:
  email:
    #recipients:
    #  - dev@lists.openshift.redhat.com
  irc:
    - "irc.freenode.org#openshift-dev"
branches:
  only:
    - ssh-option
